repos:
-   repo: https://github.com/sourcery-ai/sourcery
    rev: v1.6.0
    hooks:
    - id: sourcery
    # The best way to use Sourcery in a pre-commit hook:
    # * review only changed lines:
    # * omit the summary
      args: [--diff=git diff HEAD, --no-summary, src/]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        args: [--unsafe]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: ['--fix=auto']

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/python-poetry/poetry
    rev: '1.5.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v2.4.0'
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [build, chore, ci, docs, feat, refactor, fix, test, perf, style]

# Example of local hook
# -   repo: local
#     hooks:
#     - id: empty file contents
#       name: empty file contents
#       entry: ./scripts/empty_file_contents.sh
#       language: script
#       files: app.json
