name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Test:
    environment:
      name: production
    runs-on: ubuntu-latest
    name: Build and Test
    # env:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install poetry
        shell: bash
        run: |
          python -m pip install poetry==1.5.1

      - name: Configure poetry
        shell: bash
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m poetry install --no-root

      # - name: Code quality checks
      #   shell: bash
      #   run: |
      #     poetry run python -m black --check .

      - name: Run unit tests
        shell: bash
        run: |
          poetry run python -m pytest -xvvv tests/

      - name: Test run the tool
        if: success()
        shell: bash
        run: |
          export PYTHONPATH="${PYTHONPATH}:./src"
          python -m poetry run python src/main.py run -a

  Release:
    needs: Test
    environment:
      name: production
      url: https://pypi.org/project/python-sysinformer/
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Release
    concurrency: Release
    permissions:
      id-token: write
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install poetry
        shell: bash
        run: |
          python -m pip install poetry==1.5.1

      - name: Install dependencies
        shell: bash
        run: |
          python -m poetry install --no-root

      - name: Prepare package for release
        id: package_release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          VERSION=$(poetry run semantic-release version | grep -oE "\d+\.\d+\.\d+")
          echo "VERSION_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$VERSION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          poetry run semantic-release changelog
          poetry run semantic-release publish

      # Unable to use at the moment due to the python version used by the action
      # - name: Run Python Semantic Release
      #   id: release
      #   uses: python-semantic-release/python-semantic-release@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check publish output and terminate if no new version
        id: check_publish
        if: steps.package_release.outcome == 'success'
        run: |
          if [[ "$VERSION_OUTPUT" == *"No new version to release"* && "$VERSION_OUTPUT" == *"has already been released!"* ]]; then
            echo "No new version, exiting"
            echo "SHOULD_CONTINUE=false" >> $GITHUB_OUTPUT
          else
            echo "New version, continuing"
            echo "SHOULD_CONTINUE=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish to TestPyPI
        id: test_publish
        if: steps.package_release.outcome == 'success' && steps.check_publish.outputs.SHOULD_CONTINUE == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Test install from TestPyPI
        if: steps.test_publish.outcome == 'success' && steps.check_publish.outputs.SHOULD_CONTINUE == 'true'
        shell: bash
        id: test_install
        run: |
          python -m pip install \
          --index-url https://test.pypi.org/simple/ \
          --extra-index-url https://pypi.org/simple \
          python-sysinformer

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.test_install.outcome == 'success' && steps.check_publish.outputs.SHOULD_CONTINUE == 'true'
